- packages/components/src/molecules/Panels/ResizableColumnsPanel.stories.tsx
- packages/components/src/molecules/Panels/ResizableColumnsPanel.tsx
- packages/components/src/molecules/Panels/ResizableRowsPanel.stories.tsx
- packages/components/src/molecules/Panels/ResizableRowsPanel.tsx
- packages/components/src/molecules/Panels/index.ts
- packages/components/src/molecules/Panels/types.ts
- packages/components/src/molecules/stories/ResizablePanels.stories.tsx
> feat: resizable rows

- packages/components/package.json
- packages/components/src/index.ts
- packages/components/src/molecules/Panels/ResizableColumnsPanel.stories.tsx
- packages/components/src/molecules/Panels/ResizableRowsPanel.stories.tsx
- packages/components/src/molecules/Panels/args.tsx
- packages/components/src/molecules/Panels/index.ts
- packages/components/src/molecules/TitleBar/TitleBar.stories.tsx
- packages/components/src/molecules/TitleBar/TitleBar.styled.tsx
- packages/components/src/molecules/TitleBar/TitleBar.tsx
- packages/components/src/molecules/TitleBar/args.tsx
- packages/components/src/molecules/TitleBar/index.ts
- packages/components/src/molecules/TitleBar/types.ts
- packages/components/src/molecules/index.ts
- packages/components/src/molecules/stories/ResizablePanels.stories.tsx
- packages/components/src/styles/Colors.ts
> feat: TitleBar

- packages/tree-navigator/.gitignore
- packages/tree-navigator/README.md
- packages/tree-navigator/src/core/checkable.ts
- packages/tree-navigator/src/core/itemBuilder.ts
- packages/tree-navigator/src/core/listeners.ts
- packages/tree-navigator/src/core/rows.ts
- packages/tree-navigator/src/core/sectionBuilder.ts
- packages/tree-navigator/src/core/treeNavigator.tsx
- packages/tree-navigator/src/core/visibility.ts
- packages/tree-navigator/src/types/blueprint.ts
- packages/tree-navigator/src/types/customization.ts
- packages/tree-navigator/src/types/instance.ts
- packages/tree-navigator/src/types/navigator.ts
> refactor: simplify tree-navigator's API

- packages/components/src/molecules/ActivityBar/ActivityBar.tsx
- packages/components/src/molecules/ActivityBar/ActivityBarItem.styled.tsx
- packages/components/src/molecules/ActivityBar/ActivityBarItem.tsx
- packages/components/src/molecules/ActivityBar/types.ts
> refactor: activity bar

- packages/tree-navigator/src/components/ItemRenderer/ItemRenderer.tsx
- packages/tree-navigator/src/components/SectionRenderer/SectionRenderer.tsx
- packages/tree-navigator/src/index.ts
- packages/tree-navigator/src/types/blueprint.ts
- packages/tree-navigator/src/types/navigator.ts
> fix(tree-navigator): renderer components

- packages/tree-navigator/example/src/navigators/FileTreeNavigator.ts
- packages/tree-navigator/example/src/navigators/ResourceTreeNavigator.ts
- packages/tree-navigator/src/core/itemBuilder.ts
- packages/tree-navigator/src/core/listeners.ts
- packages/tree-navigator/src/core/rows.ts
- packages/tree-navigator/src/core/sectionBuilder.ts
- packages/tree-navigator/src/core/treeNavigator.tsx
> fix: tree navigator example

- packages/create-monokle-plugin/index.js
- packages/create-monokle-plugin/template-validation-ts/README
- packages/create-monokle-plugin/template-validation-ts/package.json
> chore: update validation-ts template

- packages/validation/src/__tests__/MonokleCustom.test.ts
- packages/validation/src/validators/custom/devValidator.ts
> fix: unload dev validator

- packages/validation/package.json
- packages/validation/src/__tests__/MonokleValidator.test.ts
- packages/validation/src/__tests__/resources/kustomize-with-relative-path-resources/ldap/base/deployment.yaml
- packages/validation/src/__tests__/resources/kustomize-with-relative-path-resources/ldap/base/kustomization.yaml
- packages/validation/src/__tests__/resources/kustomize-with-relative-path-resources/ldap/base/service.yaml
- packages/validation/src/__tests__/resources/kustomize-with-relative-path-resources/ldap/overlays/production/deployment.yaml
- packages/validation/src/__tests__/resources/kustomize-with-relative-path-resources/ldap/overlays/production/kustomization.yaml
- packages/validation/src/__tests__/resources/kustomize-with-relative-path-resources/ldap/overlays/staging/deployment.yaml
- packages/validation/src/__tests__/resources/kustomize-with-relative-path-resources/ldap/overlays/staging/kustomization.yaml
- packages/validation/src/__tests__/testUtils.ts
- packages/validation/src/references/utils/helpers.ts
This PR fixes handling of relative path refs in kustomizations - which were previously not resolved correctly
> fix: fixed resolution of relative path refs in kustomizations

- packages/validation/src/MonokleValidator.ts
- packages/validation/src/common/types.ts
- packages/validation/src/utils/error.ts
- packages/validation/src/validators/custom/devValidator.ts
- packages/validation/src/validators/open-policy-agent/validator.ts
This PR fixes slow loading of plugins
> feat: improve plugin loading

- packages/create-monokle-plugin/template-validation-ts/internal/server.cts
> feat(create-plugin): allow multiple event sources in dev server

- packages/components/package.json
This PR bumps the components version number.
-
-
> chore: components release v0.0.14

- packages/components/src/molecules/ActivityBar/types.ts
This PR fixes the types for the activity bar
-
-
> fix: correct the activity bar types

- packages/components/package.json
This PR bring the release number up to date with the one published in npm
-
-
> chore: components release v0.0.17

- packages/validation/src/__tests__/resources/kustomize-with-relative-path-resources/ldap/base/kustomization.yaml
- packages/validation/src/references/utils/kustomizeRefs.ts
This PR fixes https://github.com/kubeshop/monokle/issues/2531 in core - will backport to Desktop once approved
> fix: improved handling of external resource refs in kustomizations

- packages/validation/src/MonokleValidator.ts
- packages/validation/src/common/AbstractPlugin.ts
- packages/validation/src/common/sarif.ts
- packages/validation/src/common/types.ts
- packages/validation/src/index.ts
- packages/validation/src/types.ts
- packages/validation/src/utils/getRule.ts
- packages/validation/src/validators/custom/devValidator.ts
- packages/validation/src/validators/custom/simpleValidator.ts
- packages/validation/src/validators/kubernetes-schema/rules.ts
- packages/validation/src/validators/open-policy-agent/rules.ts
- packages/validation/src/validators/open-policy-agent/types.ts
- packages/validation/src/validators/open-policy-agent/validator.ts
- packages/validation/src/validators/resource-links/rules.ts
- packages/validation/src/validators/yaml-syntax/rules.ts
> Add warnings

- .changeset/witty-cameras-own.md
- packages/create-monokle-plugin/index.js
- packages/create-monokle-plugin/template-validation-ts/src/plugin.ts
- packages/create-monokle-plugin/template-validation-ts/src/rules/noEmptyAnnotations.ts
- packages/create-monokle-plugin/template-validation-ts/src/rules/noExternalUrl.ts
- packages/create-monokle-plugin/template-validation-ts/src/rules/sealedSecrets.ts
> Fix install instructions

- .changeset/clean-months-relate.md
- packages/validation/src/common/AbstractPlugin.ts
> fix: fix default rule config

- .changeset/gorgeous-emus-cheer.md
- packages/validation/src/__tests__/MonokleValidator.test.ts
> chore: add changeset

- .changeset/early-games-compare.md
This PR adds the changes for the next components release.
-
-
> add changes

- .changeset/weak-bugs-kiss.md
- packages/validation/docs/configuration.md
- packages/validation/src/__tests__/MonokleValidator.test.ts
- packages/validation/src/__tests__/badResources.ts
- packages/validation/src/validators/open-policy-agent/validator.ts
- packages/validation/src/validators/resource-links/rules.ts
- packages/validation/src/validators/resource-links/validator.ts
- packages/validation/src/validators/yaml-syntax/validator.ts
> fix: added option to fail missing optional refs in links validator

- .changeset/config.json
- .changeset/neat-experts-push.md
- package-lock.json
- packages/cli/package.json
- packages/cli/src/utils/command.ts
- packages/cli/tsconfig.json
- packages/validation/package.json
- packages/validation/src/references/process.ts
- packages/validation/src/references/utils/getRefMappers.ts
- packages/validation/src/references/utils/getResourceKindsWithTargetingRefs.ts
- packages/validation/src/references/utils/helpers.ts
- packages/validation/src/references/utils/refMatcher.ts
- packages/validation/src/validators/custom/simpleValidator.ts
- packages/validation/src/validators/open-policy-agent/validator.ts
> Fix cli build

- packages/cli/src/utils/extract.ts
> fix: handle empty documents in multi-resource files

- .changeset/plenty-apples-know.md
- packages/components/src/molecules/TitleBar/TitleBar.tsx
> refactor: hide description if expandable and not opened

- .changeset/twenty-hotels-allow.md
> feat: patch version

- README.md
- packages/cli/README.md
- packages/create-monokle-plugin/README.md
- packages/plugin-toolkit/README.md
- packages/validation/README.md
> docs: improve readmes

- packages/cli/package.json
- packages/create-monokle-plugin/package.json
- packages/plugin-toolkit/package.json
- packages/validation/package.json
> fix: fixed urls and keywords

- .changeset/sweet-lamps-march.md
- packages/components/src/molecules/index.ts
This PR exports TitleBarCount
-
-
> fix: export the title bar count component

- .changeset/flat-seahorses-sing.md
- packages/components/src/atoms/Icon/Icon.tsx
- packages/components/src/atoms/Icon/Icons/ClusterDashboard.tsx
- packages/components/src/atoms/Icon/Icons/index.ts
- packages/components/src/atoms/Icon/types.ts
> feat: add cluster dashboard icon

- .changeset/ninety-bees-cross.md
- package-lock.json
- packages/components/src/molecules/ActivityBar/ActivityBar.stories.tsx
- packages/components/src/molecules/ActivityBar/ActivityBarItem.styled.tsx
- packages/components/src/molecules/ActivityBar/ActivityBarItem.tsx
- packages/components/src/molecules/ActivityBar/args.tsx
- packages/components/src/molecules/ActivityBar/types.ts
> feat: add isVisible property for activity bar item

- packages/validation/src/__tests__/MonokleValidator.test.ts
- packages/validation/src/__tests__/resources/kustomize-with-relative-patch/argocd/kustomization.yaml
- packages/validation/src/__tests__/resources/kustomize-with-relative-patch/argocd/overlays/production/argocd-server-deploy-command.yaml
- packages/validation/src/references/utils/kustomizeRefs.ts
> fix: adds support for external patch refs

- packages/create-monokle-plugin/README.md
> docs: added doc on generated folder structure

- .changeset/shiny-bikes-perform.md
- packages/components/src/atoms/Icon/Icons/AllProjects.tsx
- packages/components/src/atoms/Icon/Icons/index.ts
> feat: add AllProjects icon

- .changeset/calm-queens-sip.md
- packages/components/src/atoms/Icon/Icon.tsx
- packages/components/src/atoms/Icon/types.ts
> feat: export all-projects icon

- .changeset/lazy-mayflies-switch.md
- packages/components/src/molecules/ActivityBar/ActivityBarItem.styled.tsx
> fix: line-height of small badge count

- .changeset/honest-files-bow.md
- packages/components/src/molecules/LearnPage/HelpfulResourceCard.styled.tsx
- packages/components/src/molecules/LearnPage/HelpfulResourceCard.tsx
- packages/components/src/molecules/LearnPage/LearnCard.styled.tsx
- packages/components/src/molecules/LearnPage/LearnCard.tsx
- packages/components/src/molecules/LearnPage/LearnPage.stories.tsx
- packages/components/src/molecules/LearnPage/LearnPage.styled.tsx
- packages/components/src/molecules/LearnPage/LearnPage.tsx
- packages/components/src/molecules/LearnPage/index.ts
- packages/components/src/molecules/index.ts
- packages/components/src/styles/Colors.ts
> fix: added learn page component

- .changeset/quiet-cows-join.md
- packages/components/src/molecules/LearnPage/LearnPage.tsx
- packages/components/src/molecules/LearnPage/types.ts
- Removes helpful resources that are no longer needed
-
> refactor: remove unneeded helpful resources

- packages/components/src/molecules/LearnPage/HelpfulResourceCard.tsx
- packages/components/src/molecules/LearnPage/LearnCard.tsx
- packages/components/src/molecules/LearnPage/LearnPage.tsx
- packages/components/src/molecules/LearnPage/index.ts
- packages/components/src/molecules/LearnPage/types.ts
> feat: export types + components

- .changeset/rude-oranges-doubt.md
> chore: release

- .changeset/rude-icons-provide.md
- packages/components/src/molecules/LearnPage/HelpfulResourceCard.styled.tsx
- packages/components/src/molecules/LearnPage/LearnCard.styled.tsx
- packages/components/src/molecules/LearnPage/LearnPage.styled.tsx
Adjusted spacing of LearnPage component
> fix: LearnPage spacing

- .changeset/cool-countries-sit.md
- package-lock.json
- package.json
> feat: try downgrading

- .changeset/empty-lamps-wash.md
- package-lock.json
- packages/components/package.json
- packages/components/src/index.ts
- packages/components/src/molecules/LearnPage/index.ts
- packages/components/src/molecules/index.ts
exported WalkThrough components types
> fix: export  WalkThrough types

- .changeset/curvy-steaks-relate.md
- packages/components/src/molecules/ErrorInfo/ErrorInfo.stories.args.tsx
- packages/components/src/molecules/ErrorInfo/ErrorInfo.stories.tsx
- packages/components/src/molecules/ErrorInfo/ErrorInfo.tsx
- packages/components/src/molecules/ErrorInfo/index.ts
- packages/components/src/molecules/ErrorInfo/types.ts
- packages/components/src/molecules/index.ts
> feat: ErrorInfo card

- .changeset/strong-gifts-invite.md
- packages/components/src/molecules/ValidationOverview/CollapseItemRow.tsx
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/utils.tsx
> fix: selected problem

- .changeset/angry-zebras-taste.md
> chore: add missing changeset

- .changeset/stupid-planes-hide.md
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
> fix: temporary hide filters button

- .changeset/gorgeous-geese-applaud.md
- packages/components/src/atoms/Filter/FilterHeader.tsx
This PR...
- Added Filter header actions
-
> fix: Added Filter header actions 

- .changeset/lovely-ducks-grab.md
- packages/components/src/molecules/ValidationOverview/CollapseItemRow.tsx
> refactor: styling

- .changeset/flat-humans-talk.md
- packages/components/src/atoms/Filter/Filter.tsx
> fix: pass FilterButton as optional prop to the Filter

- .changeset/two-coins-press.md
- packages/components/src/molecules/ValidationPopover/ValidationPopover.stories.args.tsx
- packages/components/src/molecules/ValidationPopover/ValidationPopover.stories.tsx
- packages/components/src/molecules/ValidationPopover/ValidationPopover.tsx
- packages/components/src/molecules/ValidationPopover/index.ts
- packages/components/src/molecules/ValidationPopover/types.ts
- packages/components/src/molecules/index.ts
> feat: validation popover

- .changeset/pretty-singers-lick.md
- packages/components/src/molecules/ProblemInfo/ProblemInfo.tsx
> refactor: ProblemInfo max-height

- .changeset/light-books-build.md
- packages/components/src/molecules/ValidationOverview/CollapseItemRow.tsx
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/constants.tsx
- packages/components/src/molecules/ValidationOverview/utils.tsx
> refactor: validation overview styling

- .changeset/sweet-days-sing.md
- packages/components/src/atoms/Filter/Filter.tsx
- packages/components/src/atoms/Filter/FilterButton.tsx
- packages/components/src/atoms/Filter/FilterForm.tsx
- packages/components/src/atoms/Filter/FilterHeader.tsx
- packages/components/src/atoms/SearchInput/SearchInput.tsx
- packages/components/src/molecules/ValidationOverview/ValidationCollapsePanelHeader.tsx
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/ValidationOverviewFilters.tsx
- packages/components/src/molecules/ValidationOverview/constants.tsx
- packages/components/src/molecules/ValidationOverview/hooks.ts
- packages/components/src/molecules/ValidationOverview/types.ts
- packages/components/src/molecules/ValidationOverview/utils.tsx
This PR...
- Add filtering by tool component
- Add filtering by warning/error
-
> feat: validation overview filters

- packages/validation/src/validators/yaml-syntax/rules.ts
- packages/validation/src/validators/yaml-syntax/validator.ts
> feat(validation): improve yaml plugin

- .changeset/spotty-avocados-whisper.md
> chore: changeset

- .changeset/green-days-admire.md
- packages/validation/src/validators/kubernetes-schema/schemaLoader.ts
- packages/validation/src/validators/open-policy-agent/validator.ts
> fix: fix schema loader

- .changeset/tame-poets-trade.md
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/types.ts
- Handle loading status directly inside core
> refactor: validation overview

- .changeset/khaki-rocks-train.md
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- Keep show by filter value when unmounting component
- Keep active keys when unmounting the component
- Small styling refactor
> fix: validation overview

- package-lock.json
> Publish monaco kubernetes

- .changeset/three-trains-mate.md
- package-lock.json
- packages/components/package.json
- packages/components/vite.config.ts
> add missing package and externalise elkjs

- .changeset/cyan-hornets-draw.md
- packages/validation/src/MonokleValidator.ts
- packages/validation/src/createExtensibleMonokleValidator.browser.ts
- packages/validation/src/validators/custom/devValidator.ts
This PR removes usage of modern private field (i.e. `#` prefix`)
> fix: fix legacy builds

- .changeset/five-donkeys-swim.md
- packages/components/src/atoms/Filter/Filter.tsx
- packages/components/src/atoms/Filter/FilterButton.tsx
> refactor: filter button styling

- .changeset/thirty-rabbits-serve.md
- packages/validation/src/common/types.ts
> fix: import

- .changeset/tall-melons-compare.md
- package-lock.json
- packages/components/package.json
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/hooks.ts
- packages/validation/package.json
- packages/validation/src/MonokleValidator.ts
- packages/validation/src/references/utils/getResourceNodes.ts
> refactor: use react-fast-compare

- .changeset/fifty-falcons-guess.md
- packages/validation/src/references/mappers/mappers.ts
> fix: owner reference

- packages/validation/README.md
- packages/validation/docs/plugin-metadata.md
> docs: fixed links to Monokle CLI

- package-lock.json
- packages/validation/package.json
- packages/validation/src/__tests__/MonokleValidator.test.ts
- packages/validation/src/references/process.ts
- packages/validation/src/references/utils/kustomizeRefs.ts
> docs: fixed tests and ssh refs in kustomizations

- .changeset/dull-beans-happen.md
- packages/components/src/molecules/Panels/ResizableColumnsPanel.tsx
- packages/components/src/molecules/Panels/types.ts
> refactor: resizable columns panel

- .changeset/nasty-cheetahs-give.md
- packages/components/src/organisms/ResourceGraph/FilterBar.tsx
- packages/components/src/organisms/ResourceGraph/ResourceGraph.tsx
- packages/components/src/organisms/ResourceGraph/types.ts
- Add the possibility to set a default namespace for the graph
> feat: add graph default namespace prop

- .changeset/real-lions-join.md
- packages/components/src/molecules/ValidationOverview/ValidationOverview.stories.args.tsx
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/utils.tsx
- packages/validation/src/utils/getRule.ts
> chore: refactor tool (ui)

- .changeset/shy-avocados-report.md
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/constants.tsx
- packages/validation/src/commonExports.ts
- packages/validation/src/index.ts
- packages/validation/src/node.ts
> fix(validation): node exports

- .changeset/wild-cooks-decide.md
- package-lock.json
- packages/validation/src/commonExports.ts
- packages/validation/src/index.ts
- packages/validation/src/node.ts
> fix validation package version

- .changeset/fresh-olives-sparkle.md
- packages/validation/src/createExtensibleMonokleValidator.browser.ts
- packages/validation/src/createExtensibleMonokleValidator.node.ts
- packages/validation/src/node.ts
- packages/validation/src/pluginLoaders/dynamicImportLoader.ts
- packages/validation/src/pluginLoaders/requireFromStringLoader.node.ts
- packages/validation/src/utils/loadCustomPlugin.node.ts
> Additional exports for validation utils

- .changeset/spotty-icons-smell.md
- packages/validation/src/index.ts
> fix validation node export

- .changeset/shiny-adults-whisper.md
- packages/validation/src/index.ts
> fix validation export type

- .changeset/rotten-seahorses-whisper.md
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/types.ts
- Select the first problem by default when opening the audit pane
> feat: validation select error by default

- .changeset/real-ladybugs-jam.md
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- Remember collapsed keys when changing activity
> refactor: validation overview collapse expand

- packages/validation/README.md
- packages/validation/docs/core-plugins.md
- packages/validation/src/validators/open-policy-agent/validator.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS106-host-ports.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS108-selinux.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS111-sysctls.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS201-volume-types.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS202-privilege-escalation.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS203-running-as-non-root.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS204-running-as-non-root-user.ts
- packages/validation/src/validators/practices/plugin.ts
> update core validator docs to include new validators

- .changeset/nervous-stingrays-search.md
- packages/components/src/molecules/ProblemInfo/ProblemInfo.tsx
> refactor: change Hint to Remediation

- .changeset/heavy-rabbits-greet.md
- packages/validation/src/__tests__/MonokleValidator.pss.test.ts
- packages/validation/src/__tests__/resources/pss-1/invalid-volume-type.yaml
- packages/validation/src/__tests__/resources/pss-1/valid-volume-type.yaml
- packages/validation/src/validators/pod-security-standards/rules/PSS201-volume-types.ts
> fix: fix volume types rule

- .changeset/eight-boats-thank.md
- packages/components/package.json
> Update styled components peer dependency versions

- .changeset/brown-mice-look.md
- packages/components/src/atoms/PaneCloseIcon/PaneCloseIcon.tsx
- packages/components/src/molecules/Panels/ResizableColumnsPanel.tsx
- packages/components/src/molecules/Panels/args.tsx
- packages/components/src/molecules/Panels/types.ts
> feat: collapsible middle pane

- .changeset/orange-kiwis-reflect.md
- .changeset/proud-horses-thank.md
- packages/validation/src/references/handleRefMappingByKey.ts
- packages/validation/src/taxonomies/cis.ts
- packages/validation/src/taxonomies/nsa.ts
- packages/validation/src/taxonomies/pss.ts
- packages/validation/src/utils/loadCustomPlugin.node.ts
- packages/validation/src/validators/kubernetes-schema/deprecation/deprecations.ts
> fix validation imports

- .changeset/purple-oranges-watch.md
- packages/components/src/molecules/ValidationOverview/utils.tsx
> fix: selected problem logic

- .changeset/grumpy-pandas-grow.md
- packages/validation/src/sarif/suppressions/plugins/AnnotationSuppressor.ts
> fix: fix annotations query

- .changeset/poor-pants-reflect.md
- packages/components/src/atoms/Icon/Icon.tsx
- packages/components/src/atoms/Icon/Icons/MagicWand.tsx
- packages/components/src/atoms/Icon/Icons/index.ts
- packages/components/src/atoms/Icon/types.ts
- packages/components/src/molecules/ProblemInfo/ProblemInfo.tsx
- packages/components/src/molecules/ProblemInfo/types.ts
- packages/components/src/molecules/ValidationOverview/ProblemRenderer.tsx
- packages/components/src/molecules/ValidationOverview/ValidationOverview.stories.args.tsx
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/constants.tsx
- packages/components/src/molecules/ValidationOverview/types.ts
- Add problem actions
- Autofix
- Suppress
- Configure
- Problem info `Configure rule` CTA
- Wrong stylings for audit pane ( colors )
> refactor: audit pane + problem info

- .changeset/hot-moose-turn.md
- .changeset/warm-turtles-pay.md
- packages/synchronizer/src/__tests__/authenticator.spec.ts
- packages/synchronizer/src/__tests__/fixtures/auth.deviceflow.yaml
- packages/synchronizer/src/utils/authenticator.ts
- packages/synchronizer/src/utils/synchronizer.ts
This PR fixes token refresh logic and introduces dedicated deep link generation methods.
- As above.
- As above.
> Fix token refresh logic + add more specific deep links

- .changeset/tall-paws-shout.md
- packages/synchronizer/src/__tests__/synchronizer.spec.ts
- packages/synchronizer/src/utils/synchronizer.ts
This PR introduces `getProjectInfo()` `synchronizer` method to be able to get related project data.
- As above.
- None.
> feat(synchronizer): introduce 'getProjectInfo()' method

- .changeset/strange-turtles-joke.md
- packages/components/src/molecules/ValidationOverview/ProblemRenderer.tsx
- packages/validation/src/validators/custom/simpleValidator.ts
- packages/validation/src/validators/custom/utils.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS101-host-process.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS102-host-namespaces.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS103-privileged-containers.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS104-capabilities.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS105-hostPath-volumes.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS106-host-ports.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS107-app-armor.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS108-selinux.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS109-proc-mount.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS110-seccomp.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS111-sysctls.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS201-volume-types.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS202-privilege-escalation.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS203-running-as-non-root.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS204-running-as-non-root-user.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS205-seccomp-strict.ts
- packages/validation/src/validators/pod-security-standards/rules/PSS206-capabilities-strict.ts
- packages/validation/src/validators/practices/rules/KBP103-drop-capabilities.ts
> Add pss autofixes

- .changeset/fluffy-toes-draw.md
- packages/components/src/molecules/ValidationOverview/ProblemRenderer.tsx
- packages/validation/src/validators/custom/simpleValidator.ts
> Polish autofixes

- .changeset/fluffy-files-melt.md
- packages/validation/src/validators/pod-security-standards/rules/PSS202-privilege-escalation.ts
> fix(validator): fix regression in PSS202

- .changeset/real-vans-type.md
- package-lock.json
- packages/validation/src/references/mappers/mappers.ts
- packages/validation/src/references/process.ts
This PR fixes crashing imports in the validation package.
- [fix] add missing .js extensions where required
> fix(core/validation): fix imports without an extension

- .changeset/fifty-colts-stare.md
- packages/validation/src/__tests__/MonokleValidator.metadata.test.ts
- packages/validation/src/validators/metadata/rules.ts
- packages/validation/src/validators/metadata/validator.ts
- Mark rule as warning by default since it is a recommended thing
- Add label/annotation key to path
> fix: metadata yaml path

- .changeset/healthy-hornets-smash.md
- packages/components/src/molecules/ProblemInfo/ProblemInfo.tsx
- packages/components/src/molecules/ProblemInfo/types.ts
- packages/components/src/molecules/ValidationOverview/ProblemRenderer.tsx
- packages/components/src/molecules/ValidationOverview/ValidationOverview.tsx
- packages/components/src/molecules/ValidationOverview/types.ts
- Add share CTA on audit pane problem / problem info component
> feat: add misconfiguration share button

- .changeset/tender-lamps-wonder.md
- packages/validation/src/__tests__/MonokleValidator.kbp.test.ts
- packages/validation/src/__tests__/MonokleValidator.test.ts
- packages/validation/src/__tests__/resources/kbp/KBP107-role.yaml
- packages/validation/src/__tests__/resources/sarif-schema.json
- packages/validation/src/validators/practices/rules/KBP107-noPodCreate.ts
- packages/validation/src/validators/practices/rules/KBP108-noPodExecute.ts
This PR fixes bugs in KBP107 and KBP108
> fix: fix no pod create/execute rules

- .changeset/cuddly-months-lie.md
- .changeset/lemon-bobcats-share.md
- package-lock.json
- packages/synchronizer/src/__tests__/apiHandler.spec.ts
- packages/synchronizer/src/handlers/apiHandler.ts
- packages/synchronizer/src/index.ts
As described in changeset. Also related to https://github.com/kubeshop/vscode-monokle/issues/47.
- None.
- As stated.
> Minor synchronizer fixes

- .changeset/ten-nails-appear.md
- packages/types/dry-run.ts
> feat: add ScriptConfig dry-run

- .changeset/tasty-tables-dress.md
- packages/validation/src/constants.ts
- packages/validation/src/pluginLoaders/PluginLoader.ts
- packages/validation/src/pluginLoaders/dynamicImportLoader.ts
- packages/validation/src/utils/loadCustomPlugin.node.ts
- packages/validation/src/validators/open-policy-agent/validator.ts
related: https://github.com/kubeshop/monokle-saas/issues/2182
> fix validation custom plugin bundle loader

- .changeset/slow-clocks-call.md
- packages/parser/src/extract.ts
This PR adds logic to guess resources if yaml invalid.
- As above.
- None.
> Add logic to guess resources if yaml invalid

- .changeset/clever-badgers-glow.md
- packages/validation/src/MonokleValidator.ts
- packages/validation/src/common/sarif.ts
- packages/validation/src/types.ts
- packages/validation/src/utils/uriBase.ts
This PR is needed for https://github.com/kubeshop/vscode-monokle/issues/73
> feat(validation): add srcroot configuration

- .changeset/chilled-houses-bow.md
- packages/parser/src/file.ts
This PR improves helm files detection.
- None.
- As above.
> Improve helm files detection

- .changeset/odd-papayas-smoke.md
- packages/parser/src/file.ts
> Helm paths check

- .changeset/khaki-meals-sit.md
- packages/validation/src/validators/practices/plugin.ts
- packages/validation/src/validators/practices/rules/KBP110-no-ssh-exposed.ts
- packages/validation/src/validators/practices/rules/KBP111-no-secret-env.ts
- packages/validation/src/validators/practices/rules/KBP112-no-secret-mounted-as-env.ts
- packages/validation/src/validators/practices/rules/KBP113-privileged-ports.ts
- packages/validation/src/validators/practices/rules/KBP114-no-exposed-service.ts
- packages/validation/src/validators/practices/rules/KBP115-mount-propagation.ts
- packages/validation/src/validators/practices/rules/KBP116-image-tagged.ts
This PR adds additional rules found in the default security policy of RHACS and gives us better compatibility with them.
> feat(validation): add additional practices rules
