package-lock.json, packages/cli/src/commands/validate.ts, packages/validation/src/MonokleConfiguration.test.ts, packages/validation/src/MonokleValidator.test.ts, packages/validation/src/MonokleValidator.ts, packages/validation/src/common/AbstractPlugin.ts, packages/validation/src/common/AbstractValidator.ts, packages/validation/src/common/types.ts, packages/validation/src/utils/abort.ts, packages/validation/src/validators/kubernetes-schema/validator.ts, packages/validation/src/validators/labels/validator.ts, packages/validation/src/validators/open-policy-agent/rules.ts, packages/validation/src/validators/open-policy-agent/types.ts, packages/validation/src/validators/open-policy-agent/validator.ts, packages/validation/src/validators/resource-links/validator.ts, packages/validation/src/validators/yaml-syntax/validator.ts
This PR improves validator:
- It fixes isPluginEnabled/isRuleEnabled and looks now at the actual validator state instead of config object.
- It embeds the validation metadata. We use this within the UI to show the validation configuration.
- It simplifies configuration (no more args and file - it was too complex and unneeded).
- It reworks the way plugins are loaded.
**Loading plugins**
A plugin will now be loaded no matter whether it is enabled or disabled. If you put it within the plugin object, we will load it. You can now after loading use the metadata to show the UI. You can still use the boolean to enable/disable it. When you remove the feature from the plugin object we will unload the validator.
=> Improve validator

packages/validation/src/validators/kubernetes-schema/validator.ts
- `getResourceValidator` accepts either a (custom) resource object or a (known) resource kind
=> fix(k8s-schema-validator): fix `warmup()` method

.changeset/two-taxis-refuse.md, packages/components/src/molecules/WalkThrough/WalkThroughCard.styles.tsx
This PR tweaks the styles to get the walkthrough height the same as the designs.
-
-
=> fix: make walkthrough modal height match the designs

packages/components/package.json, packages/components/vite.config.ts
This PR externalises antd, framer-motion, and monkle/validation
-
-
=> chore: exclude peer dependencies from bundle

packages/validation/src/__tests__/MonokleValidator.test.ts, packages/validation/src/__tests__/resources/kustomize-5.0.0-patches-and-values-files/kustomization.yaml, packages/validation/src/references/utils/kustomizeRefs.ts
This PR fixes 2 of the 3 bullets in https://github.com/kubeshop/monokle-core/issues/207
=> feat: added kustomization support for validating patches and additionalValuesFiles

.changeset/warm-dingos-dream.md, packages/validation/src/createExtensibleMonokleValidator.browser.ts, packages/validation/src/validators/custom/devValidator.ts
This PR fixes argo build. Using a literal string like this was a recommendation to get rid of `Webpack - Critical dependency: the request of a dependency is an expression`. However, a subtle side-effect is that WebPack will now bundle every file in the library, including NodeJs specific files which should've been excluded because they have a different entrypoint.
The result is that the build fails because the browser is incompatible with these NodeJs variants that rely on NodeJs standard libraries which are unavailable in the browser. Removing the string literal to a string variable will surprisingly remove this subtle effect and the build appear to succeed in first tests which were done through package linking.
=> fix: fix argo build

.changeset/strong-walls-cross.md, package-lock.json, packages/monaco-kubernetes/package.json
This PR updates monaco-kubernetes to latest validation version that fixes Argo CD build.
=> chore: version bump monaco-kubernetes

.changeset/ninety-spies-talk.md, packages/components/src/molecules/Panels/ResizableColumnsPanel.tsx
When we show hide columns in the ResizableColumnsPanel, the component loses its state. We want to maintain the state while showing/hiding columns.
=> fix: show/hide column without destroy ResizableColumnsPanel component

.changeset/polite-ducks-cover.md, packages/components/src/molecules/ValidationOverview/constants.tsx, packages/validation/src/__tests__/MonokleValidator.metadata.test.ts, packages/validation/src/__tests__/resources/metadata/replica-set.yaml, packages/validation/src/__tests__/resources/no-metadata/replica-set.yaml, packages/validation/src/common/AbstractPlugin.ts, packages/validation/src/constants.ts, packages/validation/src/createDefaultMonokleValidator.browser.ts, packages/validation/src/createDefaultMonokleValidator.node.ts, packages/validation/src/createExtensibleMonokleValidator.browser.ts, packages/validation/src/createExtensibleMonokleValidator.node.ts, packages/validation/src/index.ts, packages/validation/src/utils/findJsonPointerNode.ts, packages/validation/src/validators/kubernetes-schema/validator.ts, packages/validation/src/validators/metadata/index.ts, packages/validation/src/validators/metadata/rules.ts, packages/validation/src/validators/metadata/validator.ts
This PR introduces metadata plugin according to https://github.com/kubeshop/monokle-saas/issues/722.
- Introduce separate `metadata` validation plugin, see linked issue on detailed description how it works.
- Introduced new `preconfigureRules()` method in `AbstractPlugin` class to hook into configuration process and generate dynamic rules based on configuration, see https://github.com/kubeshop/monokle-core/pull/387/commits/7640f046db66519b432115e65e8d630d15a17284. This method transforms dynamic `config.rules` entries to full rules definitions which then are processed by the plugin the same way as predefined rules.
- Did a bit of juggling with using `defaultConfig` and `config` rule object to then validate dynamic rules correctly - …
=> Introduce metadata validation plugin

.changeset/real-bikes-boil.md, packages/validation/src/MonokleValidator.ts, packages/validation/src/createExtensibleMonokleValidator.browser.ts, packages/validation/src/createExtensibleMonokleValidator.node.ts, packages/validation/src/index.ts, packages/validation/src/node.ts, packages/validation/src/pluginLoaders/dynamicImportLoader.ts, packages/validation/src/pluginLoaders/index.node.ts, packages/validation/src/pluginLoaders/index.ts, packages/validation/src/pluginLoaders/requireFromStringLoader.node.ts
The reason for this PR is that we need to be able to customize the loading of plugins on Desktop in order to retrieve them from `<userDataDir>/validationPlugins `
- customPluginLoader can be specified when creating a new extensible validator to customize how plugins are retrieved
- exported the already implemented plugin loaders
=> refactor: allow custom plugin loaders

.changeset/wet-humans-tickle.md, packages/validation/src/__tests__/MonokleValidator.metadata.test.ts, packages/validation/src/__tests__/MonokleValidator.test.ts, packages/validation/src/common/AbstractPlugin.ts, packages/validation/src/common/sarif.ts, packages/validation/src/validators/custom/config.ts, packages/validation/src/validators/custom/simpleValidator.ts, packages/validation/src/validators/metadata/rules.ts, packages/validation/src/validators/metadata/validator.ts
This PR fixes https://github.com/kubeshop/monokle-core/issues/397.
- Introduced `configurability` field in rule definition to indicate for 3rd-parties that rule is configurable. This is required for any tools integrating with the library to  reason about rules and provide correct UI.
I'm not fully convinced about naming, we have `defaultConfiguration`, `configuration` and now `configurability`. Also `configruability` is a definition of how rule can be configured while values are passed via `configuration.parameters`, not sure if this shouldn't be merged somehow.
- None.
=> feat(validation): include configurability info in rule definition

.changeset/cool-emus-destroy.md, packages/validation/src/MonokleValidator.ts, packages/validation/src/common/AbstractPlugin.ts, packages/validation/src/common/sarif.ts, packages/validation/src/common/types.ts, packages/validation/src/utils/getRule.ts
This PR fixes #428.
- Added `results.rule.toolComponent.index` field to SARIF output. See https://github.com/kubeshop/monokle-core/issues/428#issuecomment-1614450736 for broader explanation and how it's compliant with SARIF specs.
- I still kept matching by name as a fallback.
- Same as `Changes`.
Confirmed that output is now correctly read by SARIF VSC extension with rules metadata filled:
=> fix(validation): add 'toolComponent.index' in SARIF output

.changeset/ninety-ways-pump.md, packages/validation/src/common/sarif.ts, packages/validation/src/utils/getRule.ts, packages/validation/src/validators/custom/devValidator.ts
This PR fixes bug introduced in #429 and https://github.com/kubeshop/monokle-core/actions/runs/5444228698/jobs/9901781322#step:5:35.
- Made `toolComponent.index` optional.
- Same as above.
=> Make toolComponent.index optional

.github/workflows/build.yml
This PR adds build script to be run for all pull requests targeting `main` branch.
The context for this change is that I broke release job recently because build failed (which I haven't checked locally 🙈), https://github.com/kubeshop/monokle-core/actions/runs/5444228698/jobs/9901781322#step:5:35.  With this simple check it would not have happened.
- As above.
- None.
=> ci: run build for PRs targeting main

.changeset/strange-teachers-smoke.md, packages/validation/src/__tests__/MonokleValidator.test.ts, packages/validation/src/__tests__/resources/config1.yaml, packages/validation/src/__tests__/resources/config2.yaml, packages/validation/src/config/parse.ts
This PR fixes #435.
- None.
- Fixed Zod config schema to include `settings` section.
=> fix(validation): add settings to Zod config schema for 'readConfig()'

.changeset/twelve-chicken-walk.md, packages/validation/src/utils/getRule.ts
This PR fixes invalid check which was false for `0` index while it should be `true`.
The initial idea (from #429) was to still keep matching by name as fallback. And it get broken in #432.
So instead of changing to:
```ts
const plugin = isDefined(toolPluginIndex) ? extensions[toolPluginIndex] : extensions.find(plugin => plugin.name === toolPluginName);
```
which would again lost a purpose of name check fallback, I changed it as in the code - to always have numeric index and then use it for getting plugin with `??` for fallback name check.
- As described above.
- As described above.
=> fix(validation): fix getRule toolComponent index check

packages/validation/src/__tests__/MonokleValidator.test.ts, packages/validation/src/__tests__/resources/kustomize-components/components/without-loadgenerator/delete-loadgenerator.patch.yaml, packages/validation/src/__tests__/resources/kustomize-components/components/without-loadgenerator/kustomization.yaml, packages/validation/src/__tests__/resources/kustomize-components/kustomization.yaml, packages/validation/src/constants.ts, packages/validation/src/references/utils/kustomizeRefs.ts
This PR fixes parsing of direct patch references like the following:
```
patches:
- delete-loadgenerator.patch.yaml
```
-
-
=> fix: support kustomize patches with only a Scalar path

packages/validation/src/MonokleValidator.ts, packages/validation/src/__tests__/sarif/assets/deployment.yaml, packages/validation/src/__tests__/sarif/fingerprint.test.ts, packages/validation/src/__tests__/testUtils.ts, packages/validation/src/common/AbstractPlugin.ts, packages/validation/src/common/sarif.ts, packages/validation/src/common/types.ts, packages/validation/src/config/parse.ts, packages/validation/src/utils/createLocations.ts, packages/validation/src/utils/fingerprint.ts, packages/validation/src/validators/custom/simpleValidator.ts, packages/validation/src/validators/open-policy-agent/validator.ts
This PR introduced fingerprints; you can also optionally provide a baseline validation response (e.g. the previous one or when you started your "workspace session") to see which results are new, unchanged or absent.
This could be leveraged within with the VSC Extension as baseline is prominently present there.
=> feat: add SARIF fingerprints & baseline

.changeset/silent-cars-glow.md, package-lock.json, packages/validation/package.json, packages/validation/src/MonokleValidator.ts, packages/validation/src/references/utils/getResourceNodes.ts
This PR removes react-fast-compare as it gives runtime errors due to some build tooling.
As to performance implications, there are non, all isEqual comparisons are on sets with less than 5 elements in it so this was premature optimisation
=> chore: remove react-fast-compare

.changeset/gentle-jokes-invent.md, packages/synchronizer/src/__tests__/authenticator.spec.ts, packages/synchronizer/src/__tests__/synchronizer.spec.ts, packages/synchronizer/src/constants.ts, packages/synchronizer/src/handlers/deviceFlowHandler.ts, packages/synchronizer/src/utils/synchronizer.ts
This PR changes device flow handler default configuration to prod env.
See this commit - https://github.com/kubeshop/monokle-core/pull/484/commits/9f92ffcfc06d3bfaa76b48bfd667ac0c813a3e5b, rest is just code formatting.
- As above.
- None.
=> feat(synchronizer): update device flow default configuration

.changeset/clever-rocks-travel.md, .changeset/gold-badgers-help.md, packages/synchronizer/src/handlers/storageHandler.ts, packages/synchronizer/src/handlers/storageHandlerPolicy.ts, packages/synchronizer/src/utils/authenticator.ts
This PR adds more explicit errors for storage, adds param to be able to force refresh auth token.
- As above.
- As above.
=> Synchronizer improvements

.changeset/odd-toes-compete.md, packages/synchronizer/src/__tests__/synchronizer.spec.ts, packages/synchronizer/src/handlers/apiHandler.ts, packages/synchronizer/src/utils/synchronizer.ts
This PR exposes API to get policy by project slug. This is required for https://github.com/kubeshop/monokle-cli/issues/16.
- Overloaded synchronizer policy fetching methods to allow project slug as input.
- None.
=> feat(synchronizer): expose API to get policy by project slug

.changeset/many-jobs-dress.md, packages/parser/src/extract.ts, packages/parser/src/file.ts
This PR adds Helm template files filtering needed for https://github.com/kubeshop/monokle-cli/issues/24.
- Adjusted `extractK8sResources()` method to filter Helm template files by default.
- None.
Initially I used [what Cloud does](https://github.com/kubeshop/monokle-saas/blob/c14f1c6f3bc524aa00a844016e6960f3517d8fa8/clientDomain/web/src/utils/yaml.ts#L13-L28) but recognizing Helm files based on `templates` string in file path or simple `/values.*.(yaml|yml)/` regex seems error prone (in fact one test in `validation` package was already failing due to that). So I went with recognizing Helm template files based on template syntax present in file content - `{{ ... }}`.
Now, it's not 100% perfect because I can imagine one can have a template without any `{{ ... }}` (but then it will be the …
=> feat(parser): add flag to filter helm template files

.changeset/metal-pugs-hide.md, packages/validation/src/validators/custom/simpleValidator.ts
This PR fixes lodash imports. VSC extension CommonJS compatible imports (or something like this, see message below) and so it was breaking:
```
[1] CommonJS modules can always be imported via the default export, for example using:
[1]
[1] import pkg from 'lodash';
[1] const { get, unset } = pkg;
[1] .
[1]   monokle-vsc/node_modules/@monokle/validation/lib/validators/custom/simpleValidator.js:8
[1]   import { get, unset } from 'lodash';
[1]            ^^^
[1]   SyntaxError: Named export 'get' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
[1]   CommonJS modules can always be imported via the default export, for example using:
[1]
[1]   import pkg from 'lodash';
[1]   const { get, unset } = pkg;
[1]
[1]     at …
```
=> fix(validation): fix lodash imports

.changeset/tasty-avocados-help.md, package-lock.json, packages/synchronizer/src/__tests__/apiHandler.spec.ts, packages/synchronizer/src/__tests__/authenticator.spec.ts, packages/synchronizer/src/__tests__/fixtures/auth.token.yaml, packages/synchronizer/src/__tests__/synchronizer.spec.ts, packages/synchronizer/src/handlers/apiHandler.ts, packages/synchronizer/src/handlers/storageHandler.ts, packages/synchronizer/src/handlers/storageHandlerAuth.ts, packages/synchronizer/src/models/user.ts, packages/synchronizer/src/utils/authenticator.ts, packages/synchronizer/src/utils/synchronizer.ts
This PR aligns auth header with required schema. Needed for https://github.com/kubeshop/monokle-cli/issues/25.
- None.
- Reworked API query related methods to use token object (with token and token type) instead of token string only.
=> Fix token type auth header

.changeset/famous-knives-mix.md, packages/synchronizer/src/__tests__/synchronizer.spec.ts, packages/synchronizer/src/handlers/apiHandler.ts
This PR adds more explicit GraphQL API error handling. Needed for https://github.com/kubeshop/monokle-cli/issues/25.
Due the the way it was done before, almost all errors thrown by API handler in `synchronize` resulted in _The ... project does not have policy defined. Configure it on ..._ error message which was quite confusing, when for example invalid token was used.
I added more explicit handling of such errors in ApiHandler.
- None.
- As above.
=> fix(synchronizer): add more explicit GraphQL API error handling

.changeset/pretty-donkeys-wash.md, packages/validation/src/references/mappers/mappers.ts, packages/validation/src/references/mappers/validatingAdmissionPolicyBinding.ts, packages/validation/src/references/process.ts, packages/validation/src/utils/knownResourceKinds.ts
This PR adds references for Binding.policyName -> Policy.metadata.name and Binding.paramsRef.name -> ParamsKind.metadata.name.
The params do not use the standard framework as it requires referencing the Policy to find the referenced Params which is a special case. Expanding the framework for this special edge case would complicate it too much so I kept it on the side.
=> feat: add ValidatingAdmissionPolicy references

.changeset/slimy-steaks-walk.md, packages/validation/src/__tests__/MonokleValidator.vap.test.ts, packages/validation/src/__tests__/resources/admissionPolicy/BasicValidatorResources.ts, packages/validation/src/__tests__/resources/admissionPolicy/CRDValidatorResources.ts, packages/validation/src/validators/admission-policy/types.ts, packages/validation/src/validators/admission-policy/utils.ts, packages/validation/src/validators/admission-policy/validator.ts
=> feat: handle messageExpression

.changeset/clever-years-fix.md, package-lock.json, packages/synchronizer/src/__tests__/fetcher.spec.ts, packages/synchronizer/src/createDefaultMonokleFetcher.ts, packages/synchronizer/src/handlers/apiHandler.ts, packages/synchronizer/src/utils/fetcher.ts
This PR introduces simple util for querying API directly.
This is needed in admission controller. Since some queries will be run only there I decided not to add dedicated methods for each query, just expose generic query method.
Also, it could be as simple as exposing `ApiHandler.queryApi()` (done [here](https://github.com/kubeshop/monokle-core/compare/f1ames/feat/synchronizer-query-api?expand=1#diff-ae165efda7978099364452ee8aae12dc7c6546a4d09712a4601880dd4a853593R193)) but then it would require additional error handling, passing token object, etc. Also `ApiHandler` is designed to be an internal one and exposing it would encourage direct usage. So `Fetcher` (btw. we can work on the name) util wraps it nicely and allows to just run `fetcherInstance.query(graphQlQuery)`.
- As above.
- None.
=> Add util for direct API querying

.changeset/warm-radios-hang.md, packages/synchronizer/src/index.ts
This PR adds missing synchronizer/fetcher export. Somehow missed it in #554.
- None.
- As described.
=> Add missing synchronizer/fetcher export

.changeset/tiny-lizards-perform.md, packages/synchronizer/src/handlers/apiHandler.ts, packages/synchronizer/src/utils/synchronizer.ts
This PR extends synchronizer synchronization API to allow passing project slug with path / repo data. This is useful for scenarios where integration already has project slug (e.g. it was passed by user/developer). It also reduces API requests and permissions issue (e.g. when using Automation Token, `getUser` query is not allowed and it was used to fetch project slug for repo data).
Needed for https://github.com/kubeshop/monokle-saas/issues/2037.
- As above.
- None.
=> Allow synchronization with explicit project slug

.changeset/nervous-badgers-call.md, packages/synchronizer/src/handlers/apiHandler.ts, packages/synchronizer/src/handlers/deviceFlowHandler.ts
This PR introduces explicit timeouts for API communication.
For auth it was 3500ms before which is quite short, now 10000ms. For fetch there was no explicit limit (still OS limit applies), now 30000ms.
- As above.
- As above.
=> fix(synchronizer): use explicit timeouts for API and auth queries

.changeset/three-crews-applaud.md, packages/synchronizer/src/utils/authenticator.ts
This PR provides a workaround for origin conflicts.
As described in https://github.com/kubeshop/monokle-saas/issues/2231:
> Origin conflict between integration - when CLI logged in to enterprise, VSC ext will try to use those auth credentials (e.g. refresh token) for default origin (if not yet changed).
>
> This is cumbersome in cases where I first login in with CLI and then start VSC (with Monokle ext) or when I will set origin in one workspace and then switch VSC to another project with different origin. Invalid token error occurs during extension initialization and it won't simply start which is quite an issue.
Since `refreshToken()` method is used on initialization this is enough for now to workaround this issue.
Reported a follow-up for proper handling of this …
=> fix(synchronizer): allow to clear user data on origin conflict

.changeset/friendly-papayas-lie.md, packages/validation/src/__tests__/MonokleValidator.kubernetes-schema.test.ts, packages/validation/src/__tests__/resources/deprecations-2/resources.yaml, packages/validation/src/__tests__/resources/no-apiversion/resources.yaml, packages/validation/src/validators/kubernetes-schema/rules.ts, packages/validation/src/validators/kubernetes-schema/validator.ts
This PR fixes K8S001 when the Kubernetes configuration has incorrect syntax and K8S004 which was not checking correct parameters.
=> Better kubernetes schema

.changeset/cold-cameras-camp.md, packages/synchronizer/src/createMonokleAuthenticator.ts, packages/synchronizer/src/createMonokleFetcher.ts, packages/synchronizer/src/createMonokleSynchronizer.ts, packages/synchronizer/src/handlers/apiHandler.ts, packages/synchronizer/src/handlers/configHandler.ts, packages/synchronizer/src/utils/authenticator.ts
This PR allows to pass config identifying tool/integration using library. The config is then send as `User-Agent` header with every API request. Needed for https://github.com/kubeshop/monokle-saas/issues/1904.
This follows standard format for `User-Agent` headers, for reference see:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
- https://stackoverflow.com/a/2601492
In short:
```
<product>/<product_version> <comment>
```
which in our case could be (the simplest version):
```
Monokle CLI/0.8.0
```
Then `comment` is additional data in `()`. Browsers put there OS info or similar usually, so we will have it there too:
```
Monokle CLI/0.8.0 (OS info)
```
This is also important since `ua-parser-js` library is used on the BE which can parse such OS info properly and will …
=> Pass client identity config with every API request

.changeset/silly-starfishes-breathe.md, packages/synchronizer/src/__tests__/projectSynchronizer.spec.ts, packages/synchronizer/src/createMonokleProjectSynchronizer.ts, packages/synchronizer/src/handlers/apiHandler.ts, packages/synchronizer/src/handlers/storageHandler.ts, packages/synchronizer/src/handlers/storageHandlerJsonCache.ts, packages/synchronizer/src/index.ts, packages/synchronizer/src/utils/projectSynchronizer.ts, packages/synchronizer/src/utils/synchronizer.ts
This PR is a part of https://github.com/kubeshop/vscode-monokle/issues/93.
The main goal is to allow fetching all data required for integrations at once and to allow fetched data to be used in synchronous manner.
I kept previous `synchronizer` without changes (but deprecated it) since it is used by multiple integrations. And introduced `ProjectSynchronizer` since the way it works is quite different from the previous one. Putting everything in the same class would be a mess.
The main idea is that it exposes `synchronize` method (the same as previous one) which refetches data whenever called (so this is integrator responsibility to know when to refetch). Entire response is cached and then used when `get*` methods are used. This way fetching is decoupled from getting/using data.
- Introduced …
=> feat(synchronizer): add synchronizer query to fetch all validation needed data

.changeset/blue-donkeys-sparkle.md, packages/synchronizer/src/handlers/apiHandler.ts, packages/synchronizer/src/utils/projectSynchronizer.ts
This PR allows passing suppression location.
This is needed only when suppression is first added (so the location is shown in Cloud UI). And subsequent edits (toggles does not require it.
- As above.
- As above.
=> Allow passing suppression location

.changeset/ninety-actors-reflect.md, packages/synchronizer/src/__tests__/projectSynchronizer.spec.ts, packages/synchronizer/src/handlers/apiHandler.ts, packages/synchronizer/src/utils/projectSynchronizer.ts
This PR fixes synchronization caching.
Follow-up of #599 and needed for https://github.com/kubeshop/vscode-monokle/pull/92.
- As below.
- Fixed issue with `forceSynchronization` method (and underlying cache clearing) which would still read previous, existing suppressions from cached file.
- Fixed issue when if repo owner project changes, previous cache (if exists) will be used.
- Fixed typings for `toggleSuppression` response.
- Fixed wrong cache file extension.
=> Fix synchronization cache
